### PR TITLE
Introduction of experimental feature for semi-automatic who requests

### PR DESCRIPTION
**Pull request by Ceron257**
I played around a bit and introduced two experimental features:

* trigger who request on **mouse clicks in the 3D window** (like turning the camera with mouse, interacting with things in the world, clicking players, loot mobs etc.)
* trigger who requests on **mouse clicks of most of the clickable buttons in the interface** (this includes action bars as well, so no macros are needed to issue who requests by simply casting with the mouse)

Both features require a UI reload before they will work. Unfortunately I did not figure out a way to do the same for keyboard events. But I think the first option to use the mouse is totally sufficient for now! 😉 

Beside that I removed wholib's /who command, so that the blizzard UI may handle that command correctly. However the normal who functionality still doesn't work correctly (e.g. Shift+LMB on player names shows the who window instead of simply printing the information in the chat window).

**Note**: My database got somehow deleted while developing this. I am not sure if it's connected to the changes or if something different happened.

### CODE REVIEW

**Comment by Ceron257** [comment]
It might be useful to note that blizzard's interface will silently ignore who requests if the last request is younger than 5 seconds. Wholib used to show "PLEASE WAIT" in the whoframe in that case.

**Comment by mroswald** [comment]
It seems that "world clicks" do not work for me - could it be clashing with elvui?

**Comment by Ceron257** [comment]
Maybe. I would have to reproduce it, so that I can investigate what's going on there. I heard that for example Details prevented the workaround from working, but I was unable to produce it locally even with the complete profile of the user who reported that to me. 

As many detailed information as possible would be very helpful. What AddOn exactly does prevent world clicks from working? Does it work, if you load only CensusPlus? Can you enable one AddOn after another until it breaks then? What's the minimal setup, where world clicks don't work?

As soon as I am able to reproduce it, I can have a look and try to find out what's going on there. ;)

**Comment by mroswald** [comment]
I tested locally and it's Details. Disabling Details enables the functionality.

**Comment by Ceron257** [comment]
Then I wonder why I cannot reproduce it with details. Maybe I can have a look at the weekend again.

**Comment by mroswald** [comment]
Today it worked magically - didn't change anything (not even addon updates or so). Only thing that changed: I moved and resized the details window a bit.

**Pull request merged**
