### PR TITLE
Added possibility to manually send who requests

### PR DESCRIPTION
**Pull request by Ceron257**
I played a bit around and built in the possibility to manually send who requests either with a manual who button in the user interface, or via keyboard by pressing SHIFT+T. It's not the best solution but at least, we can gather data again now.

### CODE REVIEW

**Comment by Ceron257** [comment]
These modifications however somehow "break" the official who frame syncing behavior. To get current results you would need to re-open the who list again...

**Comment by mroswald** [comment]
Tried the same last night (with console command + macro). Now found yours and would really like to see it merged :)

**Comment by Ceron257** [comment]
You could also create a makro /run ManualWho() to send a request :)

**Comment by mroswald** [comment]
Yes, I was able to do a "full" scan of Patchwerk (Alliance) today with this patch. 2k chars online, datafile looks good so far.

**Pull request merged**
